### ISSUE TITLE
Zombie Processes

### ISSUE THREAD

**Issue by zachaller** [sameersbn/docker-gitlab-ci-runner#11]
We have a project that uses gunicorn and when gunicorn stops it like to rely on init process to clean up its parent processes. This leaves zombies behind. I think it would be a good idea to possible run something like supervisord as PID 1 so that it can take care of things like that.

**Comment by sameersbn** [comment]
@zachaller supervisord already runs as PID 1. If you start your processes using supervisor, then I think it will reap the dead processes.

**Comment by zachaller** [comment]
Ok so after I was just about to start looking into doing this myself I was going through the docker files and init scripts etc and I do see that it is there. The way I was running it before was from pulling from the docker repository instead of building it from the git repo so maybe that is worth looking into.

**Comment by zachaller** [comment]
Going through the commits I see it just might be an old version on the docker repo

**Comment by sameersbn** [comment]
@zachaller do you mean old version of `docker-gitlab-ci-runner` image?

**Comment by zachaller** [comment]
Yea if you follow the readme and use 

docker pull sameersbn/gitlab-ci-runner:5.0.0-1

**Comment by sameersbn** [comment]
@zachaller got it. I just released a new `5.0.0-2` release.
