### ISSUE TITLE
Create a docker-in-docker runner

### ISSUE THREAD

**Issue by metamoof** [sameersbn/docker-gitlab-ci-runner#12]
I would like to be able to run my application tests within a docker container, without having to subclass this dockerfile.

Would it be possible to run a docker-in-docker solution?

**Comment by sameersbn** [comment]
@metamoof You dont have to base your runner on this image, but you do require gitlab-ci-runner to communicate and execute jobs for the ci server. This means that if you use dind, you will require to configure it such that gitlab-ci-runner is available and configured to talk to the ci server.

**Comment by sameersbn** [comment]
@metamoof Closing the issue. Please reopen if required
