### ISSUE TITLE
Update to the latest gitlab-ci-runner version

### ISSUE THREAD

**Issue by Jack12816** [sameersbn/docker-gitlab-ci-runner#14]
Hey Sameer,

could you upgrade to the latest version of gitlab-ci-runner (`5.2.0`)?
I opened [a issue](https://github.com/gitlabhq/gitlab-ci-runner/issues/134) on the other side to tag the missing version.
It would be great! :)

**Comment by sameersbn** [comment]
@Jack12816 yep, once a new version of gitlab-ci-runner is tagged. It will be available here.

**Comment by Jack12816** [comment]
They created the missing tags. :)
