### ISSUE TITLE
Provide ability to pass ca.crt bundle to allow https cloning

### ISSUE THREAD

**Issue by mgcrea** [sameersbn/docker-gitlab-ci-runner#16]
I had to manually add my `ca.crt` bundle chain (RapidSSL cert) inside `/usr/local/share/ca-certificates` to get the https cloning to work. Would be nice to add a `CA_CERTIFICATES_PATH` env variable.

**Comment by sameersbn** [comment]
@mgcrea Please refer to https://github.com/sameersbn/docker-gitlab-ci-runner#installing-trusted-ssl-server-certificates

**Comment by sameersbn** [comment]
@mgcrea closing as the option already exists. Reopen if you have any issue related to this. Thanks

**Comment by mgcrea** [comment]
@sameersbn indeed, I missed that, thanks.
